export const types = {

    MODAL_OPEN: 'MODAL_OPEN',
    CALENDAR_LIST: 'CALENDAR_LIST',
    CALENDAR_ACTIVE: 'CALENDAR_ACTIVE',
    CALENDAR_ADD: 'CALENDAR_ADD',
    CALENDAR_UPDATE: 'CALENDAR_UPDATE',
    CALENDAR_DELETE: 'CALENDAR_DELETE',

    AUTH_CHECKING: 'AUTH_CHECKING',
    AUTH_CHECKING_FINISH: 'AUTH_CHECKING_FINISH',
    AUTH_TOKEN_RENEW: 'AUTH_TOKEN_RENEW',
    AUTH_SIGNIN: 'AUTH_SIGNIN',
    AUTH_SIGNUP: 'AUTH_SIGNUP',
    AUTH_LOGOUT: 'AUTH_LOGOUT',

}