export const types = {

    MODAL_OPEN: 'MODAL_OPEN',
    CALENDAR_LIST: 'CALENDAR_LIST',
    CALENDAR_ACTIVE: 'CALENDAR_ACTIVE',
    CALENDAR_ADD: 'CALENDAR_ADD',
    CALENDAR_UPDATE: 'CALENDAR_UPDATE'

}